########################################################################
## Makefile for ECE1387 Assignment 1 - Parallel FPGA Router
########################################################################

VERBOSE ?= 1
ifeq ($(VERBOSE),1)
	ECHO := 
else
	ECHO := @
endif

CONF ?= debug

# the compiler
# For macOS: use g++-15 (or your installed version from homebrew)
# For Linux: change to just g++
CXX = /opt/homebrew/bin/g++-15

# target EXE
TARGET_DIR = .
TARGET = router_parallel

# the version of GTK being used
GTK_VERSION_NUM = 3.0

# the base directory of EZGL
EZGL_DIR = ezgl

# get the source files
SRCS = router_parallel.cpp $(wildcard $(EZGL_DIR)/*.cpp)
HDRS = $(wildcard ./*.h $(EZGL_DIR)/*.hpp)

# GTK includes and libs
GTK_INCLUDE_DIRS := $(shell pkg-config --cflags gtk+-$(GTK_VERSION_NUM) x11)
GTK_LIBS := $(shell pkg-config --libs gtk+-$(GTK_VERSION_NUM) x11)

# set the include directories
INC_DIRS = . $(EZGL_DIR) $(EZGL_DIR)/..

# compiler flags
CXX_FLAGS = -g -Wall -std=c++14 -fopenmp

ifeq (release, $(CONF))
	CXX_FLAGS += -O3
else ifeq (debug, $(CONF))
# Don't change anything
else
    $(error Invalid value for CONF: '$(CONF)', must be 'release' or 'debug')
endif

# 'make all' target
all: $(TARGET_DIR)/$(TARGET)

# create the exe
$(TARGET_DIR)/$(TARGET) : Makefile.parallel $(SRCS)
	$(ECHO) $(CXX) $(CXX_FLAGS) $(foreach D,$(INC_DIRS),-I$D) $(GTK_INCLUDE_DIRS) $(SRCS) $(GTK_LIBS) -o $(TARGET_DIR)/$(TARGET)

# clean the EXE 
clean:
	$(ECHO) rm -f $(TARGET_DIR)/$(TARGET)

# Test targets
test1:
	@echo "Testing parallel router with cct1.txt (distributed, 4 threads)..."
	$(ECHO) ./$(TARGET) -f cct1.txt -a distributed -t 4

test1_single:
	@echo "Testing parallel router with cct1.txt (distributed, 1 thread)..."
	$(ECHO) ./$(TARGET) -f cct1.txt -a distributed -t 1

benchmark:
	@echo "Benchmarking thread scaling on cct4.txt..."
	@echo "1 thread:"
	@./$(TARGET) -f cct4.txt -a distributed -t 1 | grep "Routing time"
	@echo "2 threads:"
	@./$(TARGET) -f cct4.txt -a distributed -t 2 | grep "Routing time"
	@echo "4 threads:"
	@./$(TARGET) -f cct4.txt -a distributed -t 4 | grep "Routing time"
	@echo "8 threads:"
	@./$(TARGET) -f cct4.txt -a distributed -t 8 | grep "Routing time"

help:
	@echo "Makefile for parallel FPGA router (OpenMP)"
	@echo ""
	@echo "Usage: "
	@echo '    > make -f Makefile.parallel'
	@echo "        Builds the parallel router executable: '$(TARGET)'"
	@echo "    > make -f Makefile.parallel clean"
	@echo "        Removes the executable"
	@echo "    > make -f Makefile.parallel test1"
	@echo "        Run with 4 threads on cct1.txt"
	@echo "    > make -f Makefile.parallel benchmark"
	@echo "        Benchmark thread scaling on cct4.txt"
	@echo ""
	@echo "Configuration Variables: "
	@echo "    CONF={release | debug}"
	@echo "        Currently set to '$(CONF)'."

.PHONY: all clean test1 test1_single benchmark help